server {
    listen 80;
    server_name _;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name your-domain.com;   # 部署时改为你的域名（生产建议配置 HTTPS 证书）

    location /api/ {
        proxy_pass http://llmops-api:5001;
        rewrite ^/api/(.*)$ /$1 break;
        include proxy.conf;
    }

    location /oauth/ {
        proxy_pass http://llmops-api:5001;
        include proxy.conf;
    }

    location /auth/ {
        proxy_pass http://llmops-api:5001;
        include proxy.conf;
    }

    location / {
        proxy_pass http://llmops-ui:3000;
        include proxy.conf;
    }

    ssl_certificate ./../ssl/llmops.crt;
    ssl_certificate_key ./../ssl/llmops.key;
    ssl_protocols TLSv1.1 TLSv1.2 TLSv1.3;
    ssl_prefer_server_ciphers on;
    ssl_session_cache shared:SSL:10m;
    ssl_session_timeout 10m;
}
